# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160604_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
